# Generated by Django 5.2 on 2025-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementpanier',
            name='jours',
            field=models.IntegerField(default=1),
        ),
    ]
