# Generated by Django 5.1.7 on 2025-10-28 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_elementpanier_jours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='car',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reservation',
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='elementpanier',
            options={'verbose_name': 'Élément du panier', 'verbose_name_plural': 'Éléments du panier'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='panier',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AddField(
            model_name='panier',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elementpanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='ecommerce.panier'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('carte', 'Carte Bancaire'), ('paypal', 'PayPal'), ('virement', 'Virement Bancaire'), ('especes', 'Espèces')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('effectue', 'Effectué'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(editable=False, max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adresse_livraison', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'profil__role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='ecommerce.commande'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('stock', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='ecommerce.categorie')),
                ('etiquettes', models.ManyToManyField(blank=True, related_name='produits', to='ecommerce.etiquette')),
                ('vendeur', models.ForeignKey(limit_choices_to={'profil__role': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='ecommerce.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.AddField(
            model_name='commentaire',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ecommerce.produit'),
        ),
        migrations.AddField(
            model_name='elementpanier',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='elementpanier',
            unique_together={('panier', 'produit')},
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('vendeur', 'Vendeur'), ('client', 'Client')], default='client', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.RemoveField(
            model_name='elementpanier',
            name='car',
        ),
        migrations.RemoveField(
            model_name='elementpanier',
            name='jours',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
