# Generated by Django 5.1.7 on 2025-10-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_etiquette_remove_car_categorie_and_more'),
    ]

    operations = [
        # Migration vide - fonctionnalité commentaires supprimée
    ]
