# Generated by Django 5.1.7 on 2025-10-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_commentaire_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='type_categorie',
            field=models.CharField(choices=[('type_vehicule', 'Type de véhicule'), ('marque', 'Marque'), ('carburant', 'Carburant'), ('segment', 'Segment'), ('etat', 'État'), ('annee', 'Année'), ('prix', 'Prix')], default='type_vehicule', max_length=20, verbose_name='Type de catégorie'),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='type_etiquette',
            field=models.CharField(choices=[('caracteristiques_speciales', 'Caractéristiques spéciales'), ('promotions', 'Promotions'), ('equipements_cles', 'Équipements clés'), ('usage', 'Usage'), ('avantages', 'Avantages'), ('etat_particulier', 'État particulier')], default='caracteristiques_speciales', max_length=30, verbose_name="Type d'étiquette"),
        ),
        migrations.AddField(
            model_name='produit',
            name='annee_fabrication',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Année de fabrication'),
        ),
        migrations.AddField(
            model_name='produit',
            name='carburant',
            field=models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], default=None, max_length=20, null=True, verbose_name='Carburant'),
        ),
        migrations.AddField(
            model_name='produit',
            name='equipements',
            field=models.JSONField(blank=True, default=list, help_text="Liste des équipements (ex: ['Climatisation', 'GPS'])", null=True, verbose_name='Équipements'),
        ),
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('reconditionne', 'Reconditionné')], default=None, max_length=20, null=True, verbose_name='État'),
        ),
        migrations.AddField(
            model_name='produit',
            name='kilometrage',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Kilométrage'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='produit',
            name='modele',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_places',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Nombre de places'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_portes',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Nombre de portes'),
        ),
        migrations.AddField(
            model_name='produit',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default=None, max_length=20, null=True, verbose_name='Transmission'),
        ),
    ]
