# Generated by Django 5.1.7 on 2025-10-31 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_favoris_delete_critique'),
    ]

    operations = [
        # Migration vide - fonctionnalité commentaires supprimée
    ]
