# Generated by Django 5.1.7 on 2025-11-03 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_commentaire_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='Approuvé'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='business_description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'activité"),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'activité"),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(limit_choices_to={'profil__approved': True, 'profil__role': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL),
        ),
    ]
