# Generated by Django 5.1.7 on 2025-11-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_profilutilisateur_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='vendeurs/id_documents/', verbose_name="Pièce d'identité"),
        ),
    ]
