# Generated by Django 5.1.7 on 2025-11-03 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_profilutilisateur_id_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['disponible', '-date_creation'], name='ecommerce_p_disponi_9701f2_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['vendeur', '-date_creation'], name='ecommerce_p_vendeur_ca4b4d_idx'),
        ),
    ]
